version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: vagamiga
      POSTGRES_USER: vagamiga
      POSTGRES_PASSWORD: vagamiga123
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://vagamiga:vagamiga123@db:5432/vagamiga
      - DEBUG=True

  frontend:
    build: ./frontend
    command: npm start
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  postgres_data: