# Generated by Django 5.2.3 on 2025-06-21 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_condominium_remove_vaga_condominio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condominium',
            options={'verbose_name': 'Condominium', 'verbose_name_plural': 'Condominiums'},
        ),
        migrations.AlterModelOptions(
            name='resident',
            options={'verbose_name': 'Resident', 'verbose_name_plural': 'Residents'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_manage_condominium', 'Can manage condominium'), ('can_view_reports', 'Can view reports')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterUniqueTogether(
            name='condominium',
            unique_together={('name', 'address')},
        ),
        migrations.AlterUniqueTogether(
            name='parkingspot',
            unique_together={('spot_name', 'condominium')},
        ),
        migrations.AlterModelTable(
            name='condominium',
            table='condominiums',
        ),
        migrations.AlterModelTable(
            name='parkingspot',
            table='parkingspots',
        ),
        migrations.AlterModelTable(
            name='report',
            table='reports',
        ),
        migrations.AlterModelTable(
            name='resident',
            table='residents',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
